"""Update orders table

Revision ID: 11d2ec55905f
Revises: dfa7a50825cc
Create Date: 2026-08-06 11:33:14.045448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d2ec55905f'
down_revision = 'dfa7a50825cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(batch_op.f('orders_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_addresses', ['address_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])
        batch_op.drop_column('total_amount')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_customer_id_fkey'), 'accounts', ['customer_id'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('discount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('address_id')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
