"""payment service update

Revision ID: 30938c2d7e0e
Revises: 7a270536de95
Create Date: 2026-08-09 10:10:43.866150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30938c2d7e0e'
down_revision = '7a270536de95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('razorpay_signature', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.drop_column('razorpay_signature')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
