"""inventory log variant nullable

Revision ID: 7a270536de95
Revises: 1b5d67fd95db
Create Date: 2026-08-06 16:01:20.841048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a270536de95'
down_revision = '1b5d67fd95db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
