"""Upgrade product model

Revision ID: 8cfd5d516a89
Revises: 2743412c646d
Create Date: 2026-08-04 16:25:33.472036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cfd5d516a89'
down_revision = '2743412c646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('compare_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'OUT_OF_STOCK', 'ARCHIVED', name='productstatus'),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.drop_constraint(batch_op.f('products_supplier_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['seller_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('short_description')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_supplier_id_fkey'), 'accounts', ['supplier_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DRAFT', 'ACTIVE', 'OUT_OF_STOCK', 'ARCHIVED', name='productstatus'),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('sku')
        batch_op.drop_column('stock')
        batch_op.drop_column('compare_price')
        batch_op.drop_column('price')
        batch_op.drop_column('category_id')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
