"""add brands and product brand relationship

Revision ID: c08203651888
Revises: 30938c2d7e0e
Create Date: 2026-08-12 21:36:52.176974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08203651888'
down_revision = '30938c2d7e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))
        batch_op.drop_column('brand_id')

    op.drop_table('brands')
    # ### end Alembic commands ###
