"""create delivery assignments

Revision ID: c7ee5919ed8a
Revises: 5f925a779c2d
Create Date: 2026-08-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ee5919ed8a'
down_revision = '5f925a779c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_assignments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=150), nullable=True),
    sa.Column('agent_phone', sa.String(length=30), nullable=True),
    sa.Column('pickup_status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', name='pickupstatus'), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.Enum('NOT_STARTED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_assignments')
    op.execute('DROP TYPE IF EXISTS pickupstatus')
    op.execute('DROP TYPE IF EXISTS deliverystatus')
    # ### end Alembic commands ###
