"""Upgrade product images

Revision ID: eb2c58c09310
Revises: b6191f4497a9
Create Date: 2026-08-05 09:55:12.105057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2c58c09310'
down_revision = 'b6191f4497a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_thumbnail', sa.Boolean(), nullable=False))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['id'])
        batch_op.drop_column('is_thumbnail')
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_thumbnail', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.drop_column('is_thumbnail')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('public_id')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
